---

- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: update repository index (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: Elastic
  become: true
  roles:
    - Elastic

- hosts: Prometheus
  become: true
  roles:
    - Prometheus

- hosts: LampStack
  become: true
  roles:
    - LampStack
