---

- name: install prometheus (Ubuntu)
  command: apt install prometheus -y
  when: ansible_distribution == "Ubuntu"

- name: install prometheus (CentOS)
  command: snap install prometheus --classic
  when: ansible_distribution == "CentOS"

- name: update repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: upgrade all pacakges
  apt:
    upgrade: dist
    force_apt_get: yes

- name: install pre-req
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common

- name: add grafana GPG key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: install the grafana package
  apt:
    name: grafana
    state: present
    update_cache: yes

