---

- name: Elastic stack on Ubuntu
  apt:
    name:
      - elasticsearch
      - kibana
      - logstash
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Nagios Ubuntu
  apt:
    name:
    - nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
